id: P010775
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01639
  title: དབང་བསྐུར་བྱིན་རླབས་སོགས་ཀྱི་རབ་དབྱེ་ཉུང་བསྡུས་བློ་དམན་ཉམས་དགའ
  author: ''
  volumes:
    721f1703f082473ab84024f746b60f1f:
      image_group_id: I00KG02937
      title: ''
      volume_number: 1
      total_pages: 20
